import Head from 'next/head';
import Image from 'next/image';
import { Avatar } from '../components/Avatar';
import { MicrophoneIcon, ViewGridIcon } from '@heroicons/react/solid';
import { SearchIcon } from '@heroicons/react/outline';
import { Footer } from '../components/Footer';
import { useRef } from 'react';
import {useRouter} from 'next/router'


export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null)

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) return;
    
    router.push(`/search?term=${term}`);
  }

  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Google Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='https://pngimg.com/uploads/google/google_PNG19630.png' />
      </Head>

      {/* header */}

      <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
        {/* left */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        {/* right */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>

          {/* icon */}

          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer' />

          {/* Avatar */}
          <Avatar url='https://img.freepik.com/free-vector/gradient-abstract-greend-blue-background-with-geometric-elements_23-2149399995.jpg?t=st=1658369764~exp=1658370364~hmac=2f76f0750b6add6647cd17400d2e5f20bd0019e11a7e28aeff987ae63fab2f12&w=1060' />
        </div>
      </header>

      {/* body */}

      <form className='flex flex-col items-center mt-44 flex-grow w-4/5'>
        <Image
          src='https://pngimg.com/uploads/google/google_PNG19644.png'
          height={130}
          width={300}
        />

        <div className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl' >
          <SearchIcon className='h-5 w-5 mr-3 text-gray-500' />
          <input ref={searchInputRef} type='text' className='flex-grow focus:outline-none '  />
          <MicrophoneIcon className='h-5 w-5' />
        </div>
        <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4'>
          <button onClick={search} className='btn'>Google Search</button>
          <button onClick={search} className='btn'>I'm Feeling Lucky</button>
        </div>
      </form>

      {/* footer */}

      <Footer />
    </div>
  );
}


// 1.29 